title: Gewaltfreie Kommunikation in Potsdam
description: >
   Eine Seite für die Hochschulgruppe "Gewaltfreie Kommunikation in Potsdam".
   Mit ausführlichen Materialien für die Gestaltung von Übungsgruppentreffen.
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "sunrise" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" 

# Site Settings
locale                   : "en-US"
title_separator          : "|"
#name                     : "Your Name"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

search                   : true

header_pages:
  - satzung.md
  
collections:
  articles:
    output: true
  exercises:
    output: true
  
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: single
      read_time: true
      classes: [wide]
      sidebar:
        nav: "mat"
  - scope:
      path: ""
      type: exercises
    values:
      layout: page
      

