title: Gewaltfreie Kommunikation in Potsdam
description: >
   Eine Seite für die Hochschulgruppe "Gewaltfreie Kommunikation in Potsdam".
   Mit ausführlichen Materialien für die Gestaltung von Übungsgruppentreffen.
theme: minima

header_pages:
