title: Gewaltfreie Kommunikation in Potsdam
description: >
   Eine Seite für die Hochschulgruppe "Gewaltfreie Kommunikation in Potsdam".
   Mit ausführlichen Materialien für die Gestaltung von Übungsgruppentreffen.
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "sunrise" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" 


header_pages:
  - satzung.md
  
collections:
  articles:
    output: true
  exercises:
    output: true
  
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: page
  - scope:
      path: ""
      type: my_collection
    values:
      layout: page
      

